### ISSUE TITLE
Error: Request failed with status code 401 and other errors

### ISSUE THREAD

**Issue by cristinav74** [FredMK/minimed-connect-to-nightscout-wrapper#2]
After the update, this error occurred immediately after starting the process (`node run.js`):
```
Error: timeout of 10000ms exceeded
stack: Error: timeout of 10000ms exceeded
    at createError (D:\NS_Medtronic\minimed-connect-to-nightscout-master\node_modules\minimed-connect-to-nightscout\node_modules\axios\lib\core\createError.js:16:15)
    at ClientRequest.handleRequestTimeout (D:\NS_Medtronic\minimed-connect-to-nightscout-master\node_modules\minimed-connect-to-nightscout\node_modules\axios\lib\adapters\http.js:256:16)
    at Object.onceWrapper (events.js:421:28)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:784:9)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

The process is working, there are some delays, but the following error keeps being displayed in the command line:
```
Error: Request failed with status code 401
stack: Error: Request failed with status code 401
    at createError (D:\NS_Medtronic\minimed-connect-to-nightscout-master\node_modules\minimed-connect-to-nightscout\node_modules\axios\lib\core\createError.js:16:15)
    at settle (D:\NS_Medtronic\minimed-connect-to-nightscout-master\node_modules\minimed-connect-to-nightscout\node_modules\axios\lib\core\settle.js:17:12)
    at D:\NS_Medtronic\minimed-connect-to-nightscout-master\node_modules\minimed-connect-to-nightscout\node_modules\axios-cookiejar-support\lib\interceptors\response.js:79:25
    at new Promise (<anonymous>)
    at responseInterceptor (D:\NS_Medtronic\minimed-connect-to-nightscout-master\node_modules\minimed-connect-to-nightscout\node_modules\axios-cookiejar-support\lib\interceptors\response.js:78:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getConnectData (D:\NS_Medtronic\minimed-connect-to-nightscout-master\node_modules\minimed-connect-to-nightscout\carelink.js:214:16)
    at async Object.fetch (D:\NS_Medtronic\minimed-connect-to-nightscout-master\node_modules\minimed-connect-to-nightscout\carelink.js:260:29)
```

**Comment by FredMK** [comment]
The timeout problem occurs when Carelink server is not responding, it happens.
401 is strange, I didn't see it on my side.

**Comment by FredMK** [comment]
Did you disabled the mmconnect plugin in Nightscout?

**Comment by cristinav74** [comment]
Yes

**Comment by cristinav74** [comment]
Your setup is used by many users in Romania these days, where there is Medtronic covered by insurance and they cannot use their NS right now.
These errors do not occur to anybody, only some users may experience them.

**Comment by FredMK** [comment]
This error occurs when the login token is not valid anymore. This can happen, when the token invalidated because of another login. For example if you login to Carelink, this error will occur. That's why I asked, that are you sure that no other system is running which is trying to login to Carelink. As the error is not occurs to me, I cannot debug the problem.

**Comment by cristinav74** [comment]
> This error occurs when the login token is not valid anymore. This can happen, when the token invalidated because of another login. For example if you login to Carelink, this error will occur. That's why I asked, that are you sure that no other system is running which is trying to login to Carelink. As the error is not occurs to me, I cannot debug the problem.

That explains a lot. Thank you.
Indeed, some users have more instances that are trying to connect to Carelink.
In my case, I am testing with the account of another person (I have his permission) and that may generate multiple logins (I do no use Medtronic myself but I try to help people).

**Comment by FredMK** [comment]
It can be reproduced, but cannot be fixed. 
Carelink does not support multi device login, and there is no problem with that.
The solution is simple, only use one system to fetch data from Carelink.
